### ISSUE TITLE
Relay SEGFAULT

### ISSUE THREAD

**Issue by uhlhosting** [cachewerk/relay#117] opened 2023-09-01 16:08 UTC
## Description

Getting segfault with relay.so on PHP 8.1
## Expected Behavior

No segfaults
## Actual Behavior

```
[root@cp tmp]# dmesg|grep relay
[3965810.756337] php-fpm[1706334]: segfault at 14 ip 00007f1e62d1615f sp 00007ffd8efe0788 error 6 in relay.so[7f1e62cd9000+8f000]
[3965858.549335] php-fpm[1709697]: segfault at 14 ip 00007f1e62d1615f sp 00007ffd8efe0788 error 6 in relay.so[7f1e62cd9000+8f000]
[5118045.878545] php-fpm[348154]: segfault at 14 ip 00007f1e62d1615f sp 00007ffd8efe0788 error 6 in relay.so[7f1e62cd9000+8f000]
[5634446.497733] php-fpm[1425606]: segfault at 4c ip 00007f9982b129d0 sp 00007fff42225758 error 6 in relay.so[7f9982ad9000+8f000]
[5634450.057105] php-fpm[1425074]: segfault at 4c ip 00007f7cc40149d0 sp 00007fff3dde5a88 error 6 in relay.so[7f7cc3fdb000+8f000]
[5634456.844889] php-fpm[1425016]: segfault at 4c ip 00007f7cc40149d0 sp 00007fff3dde5a88 error 6 in relay.so[7f7cc3fdb000+8f000]
[5634456.845154] php-fpm[1425076]: segfault at 4c ip 00007f7cc40149d0 sp 00007fff3dde5a88 error 6 in relay.so[7f7cc3fdb000+8f000]
[5634456.994548] php-fpm[1425068]: segfault at 4c ip 00007f7cc40149d0 sp 00007fff3dde5a88 error 6 in relay.so[7f7cc3fdb000+8f000]
[5634456.994585] php-fpm[1425012]: segfault at 4c ip 00007f7cc40149d0 sp 00007fff3dde5a88 error 6 in relay.so[7f7cc3fdb000+8f000]
[5634460.865158] php-fpm[1425938]: segfault at 4c ip 00007f7cc40149d0 sp 00007fff3dde5a88 error 6 in relay.so[7f7cc3fdb000+8f000]
[5634463.703164] traps: php-fpm[1425959] general protection fault ip:7f7cc3ffd710 sp:7fff3dde5b20 error:0 in relay.so[7f7cc3fdb000+8f000]
[5634469.899453] traps: php-fpm[1424484] general protection fault ip:7f7cc3ffd710 sp:7fff3dde58c0 error:0 in relay.so[7f7cc3fdb000+8f000]
[5634470.885633] traps: php-fpm[1425866] general protection fault ip:7f40f2ffd710 sp:7ffd8a7127c0 error:0 in relay.so[7f40f2fdb000+8f000]
[5634474.505731] php-fpm[1425928]: segfault at 4c ip 00007f9982b129d0 sp 00007fff42225758 error 6 in relay.so[7f9982ad9000+8f000]
[5634476.863673] php-fpm[1425869]: segfault at 7f826cd27140 ip 00007f826caa3710 sp 00007ffd17107eb0 error 4 in relay.so[7f826ca81000+8f000]
[5634478.357127] php-fpm[1426027]: segfault at 4c ip 00007f9982b129d0 sp 00007fff42225758 error 6 in relay.so[7f9982ad9000+8f000]
[5634479.241517] php-fpm[1425876]: segfault at 7fd381625140 ip 00007fd3813a1710 sp 00007fff0ad1b360 error 4 in relay.so[7fd38137f000+8f000]
[5634480.561034] php-fpm[1425883]: segfault at 7f46d4425140 ip 00007f46d41a1710 sp 00007ffffeac3ec0 error 4 in relay.so[7f46d417f000+8f000]
[5634483.399347] php-fpm[1426071]: segfault at 4c ip 00007f18bb8149d0 sp 00007fff2341e598 error 6 in relay.so[7f18bb7db000+8f000]
[5634483.591140] php-fpm[1425999]: segfault at 4c ip 00007f40f30149d0 sp 00007ffd8a712728 error 6 in relay.so[7f40f2fdb000+8f000]
[5634483.859729] traps: php-fpm[1425887] general protection fault ip:7f59928fb710 sp:7fff686b58c0 error:0 in relay.so[7f59928d9000+8f000]
[5634485.224268] traps: php-fpm[1426059] general protection fault ip:7f9982afb710 sp:7fff422257f0 error:0 in relay.so[7f9982ad9000+8f000]
[5634490.440010] php-fpm[1426025]: segfault at 4c ip 00007f826caba9d0 sp 00007ffd17107e18 error 6 in relay.so[7f826ca81000+8f000]
[5634491.604931] php-fpm[1426042]: segfault at 4c ip 00007fd3813b89d0 sp 00007fff0ad1b2c8 error 6 in relay.so[7fd38137f000+8f000]
[5634492.290745] traps: php-fpm[1424502] general protection fault ip:7f9982afb710 sp:7fff42225590 error:0 in relay.so[7f9982ad9000+8f000]
[5634494.447559] php-fpm[1426066]: segfault at 4c ip 00007f46d41b89d0 sp 00007ffffeac3e28 error 6 in relay.so[7f46d417f000+8f000]
[5634495.608685] php-fpm[1426083]: segfault at 4c ip 00007f59929129d0 sp 00007fff686b5828 error 6 in relay.so[7f59928d9000+8f000]
[5634496.880371] traps: php-fpm[1425901] general protection fault ip:7f59227fd710 sp:7ffdf3ef4cb0 error:0 in relay.so[7f59227db000+8f000]
[5634497.875628] traps: php-fpm[1425889] general protection fault ip:7fd33befb710 sp:7ffdffe6aee0 error:0 in relay.so[7fd33bed9000+8f000]
[5634499.877407] traps: php-fpm[1425892] general protection fault ip:7fd33befb710 sp:7ffdffe6aee0 error:0 in relay.so[7fd33bed9000+8f000]
[5634502.457850] php-fpm[1426188]: segfault at 4c ip 00007fd33bf129d0 sp 00007ffdffe6ae48 error 6 in relay.so[7fd33bed9000+8f000]
[5634510.503316] php-fpm[1426180]: segfault at 4c ip 00007f59228149d0 sp 00007ffdf3ef4c18 error 6 in relay.so[7f59227db000+8f000]
[5634551.963207] traps: php-fpm[1426123] general protection fault ip:7f40f2ffd710 sp:7ffd8a7127c0 error:0 in relay.so[7f40f2fdb000+8f000]
[5634552.214271] traps: php-fpm[1426113] general protection fault ip:7f18bb7fd710 sp:7fff2341e630 error:0 in relay.so[7f18bb7db000+8f000]
[5634555.650485] php-fpm[1426330]: segfault at 4c ip 00007f40f30149d0 sp 00007ffd8a712728 error 6 in relay.so[7f40f2fdb000+8f000]
[5634558.947184] php-fpm[1426174]: segfault at 7f826cd27140 ip 00007f826caa3710 sp 00007ffd17107eb0 error 4 in relay.so[7f826ca81000+8f000]
[5634560.329716] php-fpm[1426183]: segfault at 7fd381625140 ip 00007fd3813a1710 sp 00007fff0ad1b360 error 4 in relay.so[7fd38137f000+8f000]
[5634561.625293] php-fpm[1426347]: segfault at 4c ip 00007f826caba9d0 sp 00007ffd17107e18 error 6 in relay.so[7f826ca81000+8f000]
[5634561.940032] traps: php-fpm[1426206] general protection fault ip:7fd33befb710 sp:7ffdffe6aee0 error:0 in relay.so[7fd33bed9000+8f000]
[5634562.653035] php-fpm[1426210]: segfault at 7f46d4425140 ip 00007f46d41a1710 sp 00007ffffeac3ec0 error 4 in relay.so[7f46d417f000+8f000]
[5634563.953192] traps: php-fpm[1426221] general protection fault ip:7f59928fb710 sp:7fff686b58c0 error:0 in relay.so[7f59928d9000+8f000]
[5634565.631190] php-fpm[1426350]: segfault at 4c ip 00007fd3813b89d0 sp 00007fff0ad1b2c8 error 6 in relay.so[7fd38137f000+8f000]
[5634569.636662] php-fpm[1426365]: segfault at 4c ip 00007f46d41b89d0 sp 00007ffffeac3e28 error 6 in relay.so[7f46d417f000+8f000]
[5634570.532903] php-fpm[1426369]: segfault at 4c ip 00007f59929129d0 sp 00007fff686b5828 error 6 in relay.so[7f59928d9000+8f000]
[5634570.948997] traps: php-fpm[1426246] general protection fault ip:7fd33befb710 sp:7ffdffe6aee0 error:0 in relay.so[7fd33bed9000+8f000]
[5634572.632268] php-fpm[1426414]: segfault at 4c ip 00007f09f72149d0 sp 00007ffecc269df8 error 6 in relay.so[7f09f71db000+8f000]
[5634577.737169] php-fpm[1426430]: segfault at 4c ip 00007fc1def129d0 sp 00007fff69b35e48 error 6 in relay.so[7fc1deed9000+8f000]
[5634578.586386] php-fpm[1426362]: segfault at 4c ip 00007fd33bf129d0 sp 00007ffdffe6ae48 error 6 in relay.so[7fd33bed9000+8f000]
[5634578.956141] traps: php-fpm[1426271] general protection fault ip:7f59227fd710 sp:7ffdf3ef4cb0 error:0 in relay.so[7f59227db000+8f000]
[5634582.772023] php-fpm[1426448]: segfault at 4c ip 00007f86d6f129d0 sp 00007ffdd1142ff8 error 6 in relay.so[7f86d6ed9000+8f000]
[5634584.794656] php-fpm[1426469]: segfault at 4c ip 00007f87730149d0 sp 00007ffe2acee928 error 6 in relay.so[7f8772fdb000+8f000]
[5634586.646727] php-fpm[1426446]: segfault at 4c ip 00007f59228149d0 sp 00007ffdf3ef4c18 error 6 in relay.so[7f59227db000+8f000]
[5634587.804034] php-fpm[1426494]: segfault at 4c ip 00007fecc95b89d0 sp 00007ffdec1cc368 error 6 in relay.so[7fecc957f000+8f000]
[5634592.861143] php-fpm[1426503]: segfault at 4c ip 00007f59228149d0 sp 00007ffdf3ef4c18 error 6 in relay.so[7f59227db000+8f000]
[5634597.895743] php-fpm[1426418]: segfault at 4c ip 00007f46d41b89d0 sp 00007ffffeac3e28 error 6 in relay.so[7f46d417f000+8f000]
[5634602.920214] php-fpm[1426409]: segfault at 4c ip 00007fd3813b89d0 sp 00007fff0ad1b2c8 error 6 in relay.so[7fd38137f000+8f000]
[5634607.942055] php-fpm[1426381]: segfault at 4c ip 00007f826caba9d0 sp 00007ffd17107e18 error 6 in relay.so[7f826ca81000+8f000]
[5634608.849229] php-fpm[1426511]: segfault at 4c ip 00007f59228149d0 sp 00007ffdf3ef4c18 error 6 in relay.so[7f59227db000+8f000]
[5634612.959772] php-fpm[1426408]: segfault at 4c ip 00007fd33bf129d0 sp 00007ffdffe6ae48 error 6 in relay.so[7fd33bed9000+8f000]
[5634613.418524] php-fpm[1426535]: segfault at 4c ip 00007f59228149d0 sp 00007ffdf3ef4c18 error 6 in relay.so[7f59227db000+8f000]
[5634614.280883] traps: php-fpm[1426331] general protection fault ip:7f18bb7fd710 sp:7fff2341e630 error:0 in relay.so[7f18bb7db000+8f000]
[5634618.029505] php-fpm[1426423]: segfault at 4c ip 00007f59929129d0 sp 00007fff686b5828 error 6 in relay.so[7f59928d9000+8f000]
[5634621.672400] traps: php-fpm[1424563] general protection fault ip:7f59227fd710 sp:7ffdf3ef4a50 error:0 in relay.so[7f59227db000+8f000]
[5634623.038778] traps: php-fpm[1426355] general protection fault ip:7f40f2ffd710 sp:7ffd8a7127c0 error:0 in relay.so[7f40f2fdb000+8f000]
[5634623.076260] php-fpm[1426506]: segfault at 4c ip 00007f87730149d0 sp 00007ffe2acee928 error 6 in relay.so[7f8772fdb000+8f000]
[5634628.133479] php-fpm[1426627]: segfault at 4c ip 00007f40f30149d0 sp 00007ffd8a712728 error 6 in relay.so[7f40f2fdb000+8f000]
[5634633.152672] php-fpm[1426587]: segfault at 4c ip 00007f18bb8149d0 sp 00007fff2341e598 error 6 in relay.so[7f18bb7db000+8f000]
[5634634.362670] php-fpm[1426588]: segfault at 4c ip 00007f826caba9d0 sp 00007ffd17107e18 error 6 in relay.so[7f826ca81000+8f000]
[5634634.684953] php-fpm[1426669]: segfault at 4c ip 00007f40f30149d0 sp 00007ffd8a712728 error 6 in relay.so[7f40f2fdb000+8f000]
[5634638.367670] php-fpm[1426558]: segfault at 4c ip 00007fd3813b89d0 sp 00007fff0ad1b2c8 error 6 in relay.so[7fd38137f000+8f000]
[5634641.064669] traps: php-fpm[1426441] general protection fault ip:7f09f71fd710 sp:7ffecc269e90 error:0 in relay.so[7f09f71db000+8f000]
[5634641.997765] php-fpm[1426543]: segfault at 4c ip 00007f46d41b89d0 sp 00007ffffeac3e28 error 6 in relay.so[7f46d417f000+8f000]
[5634642.695717] php-fpm[1426711]: segfault at 4c ip 00007f46d41b89d0 sp 00007ffffeac3e28 error 6 in relay.so[7f46d417f000+8f000]
[5634646.666617] traps: php-fpm[1426475] general protection fault ip:7fc1deefb710 sp:7fff69b35ee0 error:0 in relay.so[7fc1deed9000+8f000]
[5634646.728317] php-fpm[1426630]: segfault at 4c ip 00007f59929129d0 sp 00007fff686b5828 error 6 in relay.so[7f59928d9000+8f000]
[5634648.049729] traps: php-fpm[1426485] general protection fault ip:7fd33befb710 sp:7ffdffe6aee0 error:0 in relay.so[7fd33bed9000+8f000]
[5634648.834335] php-fpm[1426734]: segfault at 4c ip 00007f46d41b89d0 sp 00007ffffeac3e28 error 6 in relay.so[7f46d417f000+8f000]
[5634649.090898] php-fpm[1426742]: segfault at 4c ip 00007f46d41b89d0 sp 00007ffffeac3e28 error 6 in relay.so[7f46d417f000+8f000]
[5634652.249685] traps: php-fpm[1426498] general protection fault ip:7f86d6efb710 sp:7ffdd1143090 error:0 in relay.so[7f86d6ed9000+8f000]
[5634654.785745] php-fpm[1426605]: segfault at 4c ip 00007fd33bf129d0 sp 00007ffdffe6ae48 error 6 in relay.so[7fd33bed9000+8f000]
[5634656.185519] php-fpm[1424532]: segfault at 7f46d4425140 ip 00007f46d41a1710 sp 00007ffffeac3c60 error 4 in relay.so[7f46d417f000+8f000]
[5634657.235522] php-fpm[1426517]: segfault at 7fecc9825140 ip 00007fecc95a1710 sp 00007ffdec1cc400 error 4 in relay.so[7fecc957f000+8f000]
[5634680.810238] php-fpm[1426672]: segfault at 4c ip 00007f40f30149d0 sp 00007ffd8a712728 error 6 in relay.so[7f40f2fdb000+8f000]
[5634687.625141] traps: php-fpm[1426703] general protection fault ip:7f40f2ffd710 sp:7ffd8a7127c0 error:0 in relay.so[7f40f2fdb000+8f000]
[5634692.328357] traps: php-fpm[1426650] general protection fault ip:7f8772ffd710 sp:7ffe2acee9c0 error:0 in relay.so[7f8772fdb000+8f000]
[5634694.293310] traps: php-fpm[1424513] general protection fault ip:7f40f2ffd710 sp:7ffd8a712560 error:0 in relay.so[7f40f2fdb000+8f000]
[5634701.367340] traps: php-fpm[1426690] general protection fault ip:7f18bb7fd710 sp:7fff2341e630 error:0 in relay.so[7f18bb7db000+8f000]
[5634703.085285] php-fpm[1426698]: segfault at 7f826cd27140 ip 00007f826caa3710 sp 00007ffd17107eb0 error 4 in relay.so[7f826ca81000+8f000]
[5634703.129908] traps: php-fpm[1426710] general protection fault ip:7f09f71fd710 sp:7ffecc269e90 error:0 in relay.so[7f09f71db000+8f000]
[5634705.472106] php-fpm[1426717]: segfault at 7fd381625140 ip 00007fd3813a1710 sp 00007fff0ad1b360 error 4 in relay.so[7fd38137f000+8f000]
[5634705.643064] php-fpm[1426893]: segfault at 4c ip 00007f826caba9d0 sp 00007ffd17107e18 error 6 in relay.so[7f826ca81000+8f000]
[5634708.728244] traps: php-fpm[1426726] general protection fault ip:7fc1deefb710 sp:7fff69b35ee0 error:0 in relay.so[7fc1deed9000+8f000]
[5634710.111188] traps: php-fpm[1426741] general protection fault ip:7fd33befb710 sp:7ffdffe6aee0 error:0 in relay.so[7fd33bed9000+8f000]
[5634710.787867] php-fpm[1426903]: segfault at 4c ip 00007fd3813b89d0 sp 00007fff0ad1b2c8 error 6 in relay.so[7fd38137f000+8f000]
[5634714.319067] traps: php-fpm[1426754] general protection fault ip:7f86d6efb710 sp:7ffdd1143090 error:0 in relay.so[7f86d6ed9000+8f000]
[5634715.123220] traps: php-fpm[1426759] general protection fault ip:7f59928fb710 sp:7fff686b58c0 error:0 in relay.so[7f59928d9000+8f000]
[5634719.295138] php-fpm[1426786]: segfault at 7fecc9825140 ip 00007fecc95a1710 sp 00007ffdec1cc400 error 4 in relay.so[7fecc957f000+8f000]
[5634721.709107] php-fpm[1426946]: segfault at 4c ip 00007f59929129d0 sp 00007fff686b5828 error 6 in relay.so[7f59928d9000+8f000]
[5634723.124470] traps: php-fpm[1426798] general protection fault ip:7fd33befb710 sp:7ffdffe6aee0 error:0 in relay.so[7fd33bed9000+8f000]
[5634729.720915] php-fpm[1426925]: segfault at 4c ip 00007fd33bf129d0 sp 00007ffdffe6ae48 error 6 in relay.so[7fd33bed9000+8f000]
[5634752.419973] php-fpm[1427006]: segfault at 4c ip 00007f59929129d0 sp 00007fff686b5828 error 6 in relay.so[7f59928d9000+8f000]
[5634753.385861] traps: php-fpm[1426851] general protection fault ip:7f8772ffd710 sp:7ffe2acee9c0 error:0 in relay.so[7f8772fdb000+8f000]
[5634760.045885] php-fpm[1427058]: segfault at 4c ip 00007f59929129d0 sp 00007fff686b5828 error 6 in relay.so[7f59928d9000+8f000]
[5634763.424164] traps: php-fpm[1426887] general protection fault ip:7f18bb7fd710 sp:7fff2341e630 error:0 in relay.so[7f18bb7db000+8f000]
[5634765.190824] traps: php-fpm[1426894] general protection fault ip:7f09f71fd710 sp:7ffecc269e90 error:0 in relay.so[7f09f71db000+8f000]
[5634766.948176] traps: php-fpm[1424536] general protection fault ip:7f59928fb710 sp:7fff686b5650 error:0 in relay.so[7f59928d9000+8f000]
[5634770.793960] traps: php-fpm[1426912] general protection fault ip:7fc1deefb710 sp:7fff69b35ee0 error:0 in relay.so[7fc1deed9000+8f000]
[5634774.155571] php-fpm[1426930]: segfault at 7f826cd27140 ip 00007f826caa3710 sp 00007ffd17107eb0 error 4 in relay.so[7f826ca81000+8f000]
[5634775.379883] traps: php-fpm[1426940] general protection fault ip:7f86d6efb710 sp:7ffdd1143090 error:0 in relay.so[7f86d6ed9000+8f000]
[5634776.277951] php-fpm[1426984]: segfault at 4c ip 00007fecc95b89d0 sp 00007ffdec1cc368 error 6 in relay.so[7fecc957f000+8f000]
[5634778.545790] php-fpm[1426951]: segfault at 7fd381625140 ip 00007fd3813a1710 sp 00007fff0ad1b360 error 4 in relay.so[7fd38137f000+8f000]
[5634782.985886] php-fpm[1427121]: segfault at 4c ip 00007f826caba9d0 sp 00007ffd17107e18 error 6 in relay.so[7f826ca81000+8f000]
[5634785.184033] traps: php-fpm[1427000] general protection fault ip:7fd33befb710 sp:7ffdffe6aee0 error:0 in relay.so[7fd33bed9000+8f000]
[5634789.922050] php-fpm[1427141]: segfault at 4c ip 00007fd3813b89d0 sp 00007fff0ad1b2c8 error 6 in relay.so[7fd38137f000+8f000]
[5634797.193925] traps: php-fpm[1427037] general protection fault ip:7fd33befb710 sp:7ffdffe6aee0 error:0 in relay.so[7fd33bed9000+8f000]
[5634809.947646] php-fpm[1427174]: segfault at 4c ip 00007fd33bf129d0 sp 00007ffdffe6ae48 error 6 in relay.so[7fd33bed9000+8f000]
[5634815.446654] traps: php-fpm[1427056] general protection fault ip:7f8772ffd710 sp:7ffe2acee9c0 error:0 in relay.so[7f8772fdb000+8f000]
[5634825.485037] traps: php-fpm[1427087] general protection fault ip:7f18bb7fd710 sp:7fff2341e630 error:0 in relay.so[7f18bb7db000+8f000]
[5634827.253177] traps: php-fpm[1427091] general protection fault ip:7f09f71fd710 sp:7ffecc269e90 error:0 in relay.so[7f09f71db000+8f000]
[5634832.855745] traps: php-fpm[1427106] general protection fault ip:7fc1deefb710 sp:7fff69b35ee0 error:0 in relay.so[7fc1deed9000+8f000]
[5634837.452625] traps: php-fpm[1427129] general protection fault ip:7f86d6efb710 sp:7ffdd1143090 error:0 in relay.so[7f86d6ed9000+8f000]
[5634838.302633] php-fpm[1427238]: segfault at 4c ip 00007fd3813b89d0 sp 00007fff0ad1b2c8 error 6 in relay.so[7fd38137f000+8f000]
[5634844.414327] php-fpm[1427163]: segfault at 7fecc9825140 ip 00007fecc95a1710 sp 00007ffdec1cc400 error 4 in relay.so[7fecc957f000+8f000]
[5634845.858640] php-fpm[1425829]: segfault at 7fecc9825140 ip 00007fecc95a1710 sp 00007ffdec1cc1a0 error 4 in relay.so[7fecc957f000+8f000]
[5634845.862350] traps: php-fpm[1425505] general protection fault ip:7f86d6efb710 sp:7ffdd1142e30 error:0 in relay.so[7f86d6ed9000+8f000]
[5634845.863110] traps: php-fpm[1424609] general protection fault ip:7f18bb7fd710 sp:7fff2341e3d0 error:0 in relay.so[7f18bb7db000+8f000]
[5634845.874494] php-fpm[1424522]: segfault at 7f826cd27140 ip 00007f826caa3710 sp 00007ffd17107c50 error 4 in relay.so[7f826ca81000+8f000]
[5634845.875157] traps: php-fpm[1424465] general protection fault ip:7f09f71fd710 sp:7ffecc269c30 error:0 in relay.so[7f09f71db000+8f000]
[5634845.884636] php-fpm[1424471]: segfault at 7fd381625140 ip 00007fd3813a1710 sp 00007fff0ad1b100 error 4 in relay.so[7fd38137f000+8f000]
[5634845.892295] traps: php-fpm[1424672] general protection fault ip:7f8772ffd710 sp:7ffe2acee760 error:0 in relay.so[7f8772fdb000+8f000]
[5634845.893458] traps: php-fpm[1424968] general protection fault ip:7fc1deefb710 sp:7fff69b35c80 error:0 in relay.so[7fc1deed9000+8f000]
[5634845.906349] traps: php-fpm[1424542] general protection fault ip:7fd33befb710 sp:7ffdffe6ac80 error:0 in relay.so[7fd33bed9000+8f000]
```
## Steps to Reproduce

1. Relay was manually deployed
2. After some time the segfaults started to show up.
3.
4.

## Additional context

This is causing excessive segfaults in dmesg.

## Relay diagnostics

```
[root@cp tmp]# php --ri relay

relay

Relay Support => enabled
Relay Version => 0.6.3
Available cache => 16723008
Available serializers => php, json, igbinary, msgpack
Available compression => lzf, zstd, lz4
Binary UUID => dc27fc13-9ace-4e4f-847c-9d8df19bc33d
Git SHA => 57579a9e447f8765c80b3171e9186c1b8332b497
Allocator => relay
License state => unknown
License memory cap => 0
License request id =>  
relay.enabled => true
relay.key =>  
relay.maxmemory => 16777216
relay.maxmemory_pct => 75
relay.eviction_policy => lru
relay.eviction_sample_keys => 128
relay.initial_readers => 128
relay.invalidation_poll_usec => 5
relay.pconnect_default => 1
relay.max_endpoint_dbs => 32
relay.loglevel => none
relay.logfile =>
```

## Environment

* Operating System and version: Rocky Linux 8.8
* PHP version: PHP 8.1.23 (cli) (built: Sep  1 2023 02:48:06) (NTS)

**Comment by michael-grunder** [comment] 2023-09-01 16:35
Thanks for the report,

Is it possible for you to upgrade to `v0.6.6`?  There were known crashes fixed since `v0.6.3`. 

Also, in the logs you reported there should be an additional line (typically in `/var/log/kern.log`) that provides hexadecimal code:

Here's an example of what the `code` bits look like from a segfault I caused on purpose.

```bash
Aug 28 11:26:40 cthulhu kernel: [576592.374942] php[3172746]: segfault at 4000 ip 00007fc2e69ca04c sp 00007fff6bf6fa40 error 4 in libhiredis.so.1.2.1-dev[7fc2e69be000+d000] likely on CPU 0 (core 0, socket 0)
Aug 28 11:26:40 cthulhu kernel: [576592.374956] Code: 81 ec d8 00 00 00 48 89 74 24 28 64 48 8b 04 25 28 00 00 00 48 89 84 24 c8 00 00 00 31 c0 48 85 f6 74 07 48 c7 06 00 00 00 00 <8b> 45 00 89 44 24 24 85 c0 0f 85 fe 05 00 00 48 83 bd 98 00 00 00
```

With that code information I can narrow down exactly where Relay is crashing which would help determine if this is fixed in a newer version as well.

**Comment by tillkruss** [comment] 2023-09-01 16:36
How are you using Relay, any framework, package or plugin?

**Comment by uhlhosting** [comment] 2023-09-01 19:05
@wordpress with your plugin.

**Comment by tillkruss** [comment] 2023-09-04 19:02
@uhlhosting: Redis Object Cache or Object Cache Pro?

Let us know if this still occurs with v0.6.6, which includes several fixes.

**Comment by michael-grunder** [comment] 2023-09-05 18:36
@uhlhosting Are you able to get me the next couple lines in your grep?

e.g. `[root@cp tmp]# dmesg|grep relay -A1`

The kernel will dump hex code that I can use to identify where Relay is crashing:

```❯ grep segfault /var/log/kern.log -A1
Sep  5 11:34:01 cthulhu kernel: [607239.113392] a.out[359902]: segfault at 0 ip 000055fdb21fa13d sp 00007fff346a7250 error 6 in a.out[55fdb21fa000+1000] likely on CPU 0 (core 0, socket 0)
Sep  5 11:34:01 cthulhu kernel: [607239.113402] Code: 5d c3 0f 1f 00 c3 0f 1f 80 00 00 00 00 f3 0f 1e fa e9 77 ff ff ff f3 0f 1e fa 55 48 89 e5 48 c7 45 f8 00 00 00 00 48 8b 45 f8 <c7> 00 2a 00 00 00 b8 00 00 00 00 5d c3 00 00 f3 0f 1e fa 48 83 ec
```

Also,

```Relay Version => 0.6.3```

It's possible we have already fixed this crash, but I will investigate anyway if you can get me the above info from the kernel log.

**Comment by uhlhosting** [comment] 2023-09-06 10:16
This is after upgrading to latest release

**Comment by michael-grunder** [comment] 2023-09-06 22:11
Thanks for the updated info. Unfortunately I'm not having a lot of luck pinpointing where this is in the binary.  Can you confirm for me the precise `relay.so` or `relay-pkg.so` you are installing?

Is it [this one](wget https://builds.r2.relay.so/v0.6.7/relay-v0.6.7-php8.1-centos8-x86-64.tar.gz)?  Honestly you could even just upload the binary here so we can be sure.

**Comment by uhlhosting** [comment] 2023-09-07 07:17
I follow the steps as in the official docs for manual deployment.

**Comment by bjarn** [comment] 2023-09-11 20:00
Hi! I see error 4 mentioned in these logs, too - so might this be related to https://github.com/cachewerk/relay/issues/94?

I sadly moved away from Relay at the moment, aiming to return in the future. So, I haven't been able to get new logs. But I thought I'd drop it here and watch the issue :)

**Comment by tillkruss** [comment] 2023-09-11 20:43
@uhlhosting: Would you you mind posting `ldd /path/to/relay.so`?

**Comment by michael-grunder** [comment] 2023-09-11 20:43
> Hi! I see error 4 mentioned in these logs, too - so might this be related to https://github.com/cachewerk/relay/issues/94?

Can I get the `/var/log/kern.log` lines?  That will tell me where it's occurring in v0.6.7.

It's tough to track something like this down without any way to replicate the problem.

**Comment by michael-grunder** [comment] 2023-09-11 20:46
> @uhlhosting: Would you you mind posting ldd /path/to/relay.so?

Ideally, we'd like to see `ldd /path/to/relay.so` and `ldd /path/to/php-fpm`.

Based on where it's crashing, it could be as simple as an OpenSSL v1.x vs OpenSSL v3.x issue.

**Comment by bjarn** [comment] 2023-09-12 08:04
> > @uhlhosting: Would you you mind posting ldd /path/to/relay.so?
> 
> Ideally, we'd like to see `ldd /path/to/relay.so` and `ldd /path/to/php-fpm`.
> 
> Based on where it's crashing, it could be as simple as an OpenSSL v1.x vs OpenSSL v3.x issue.

This is very interesting, now you say so.

I experienced a _lot_ of issues with v3.x (triple the load + response times when using curl with https for example), and there's been an open issue for that for years now.

Because of this, I downgraded to v1.1.1 very recently. Will move back to Relay soon! Curious how it will perform because of this.

Don't have the kern log lines of the errors for the same reason, it's been too long haha :)

**Comment by bjarn** [comment] 2023-09-25 12:29
Since downgrading to v1.1.1, and upgrading Relay to v0.6.7, I have not yet experienced any of these segfaults.

Still keeping a close eye out on it, but just letting you know.

**Comment by michael-grunder** [comment] 2023-09-25 19:11
Thanks for the update.  If it does occur again drop the kern.log lines and I can pinpoint where the issue is.

Also, I have added a few diagnostic improvements that will be in the next version of Relay to make tracking this stuff down easier.

**Closed** 2024-01-02 19:16 UTC
Labels: bug
